# needs mingw-w64 and raylib installed
# generated by claude, windows scripting is lost on me :(

param(
    [switch]$Clean,
    [switch]$Run
)

$CC = "gcc"
$CFLAGS = "-std=c99 -O2 -Wall -Wextra -Werror=implicit-function-declaration"
$INCS = "-Iinclude"
$SRCS = @(
    "src/main.c",
    "src/game.c",
    "src/board.c",
    "src/input.c",
    "src/ui.c",
    "src/puzzle_loader.c",
    "src/generator.c",
    "src/config.c"
)
$LIBS = "-lraylib -lm -lpthread -ldl -lwinmm -lgdi32 -lopengl32"
$TARGET = "sudoku.exe"

if ($Clean) {
    Write-Host "Cleaning build files..."
    Remove-Item "*.obj" -ErrorAction SilentlyContinue
    Remove-Item $TARGET -ErrorAction SilentlyContinue
    exit 0
}

if ($Run) {
    if (Test-Path $TARGET) {
        Write-Host "Running $TARGET..."
        & ".\$TARGET"
    } else {
        Write-Host "Executable not found. Run build script first."
        exit 1
    }
    exit 0
}

Write-Host "Building Sudoku for Windows..."

# Create object files
foreach ($src in $SRCS) {
    Write-Host "Compiling $src..."
    $obj = $src -replace '\.c$', '.obj'

    # Create directory if it doesn't exist
    $dir = Split-Path $obj -Parent
    if ($dir -and !(Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }

    & $CC $CFLAGS.Split() $INCS.Split() -c -o $obj $src
    if ($LASTEXITCODE -ne 0) {
        Write-Host "Build failed!" -ForegroundColor Red
        exit 1
    }
}

Write-Host "Linking $TARGET..."
& $CC $CFLAGS.Split() $INCS.Split() -o $TARGET $SRCS -replace '\.c$', '.obj' $LIBS.Split()
if ($LASTEXITCODE -ne 0) {
    Write-Host "Build failed!" -ForegroundColor Red
    exit 1
}

Write-Host "Build successful! Run with: .\$TARGET" -ForegroundColor Green
